# Generated by Django 2.2.10 on 2020-07-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200716_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='mark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
